### ISSUE TITLE
can't complie please send me compiled exe

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [HworangeRival/Telegram_BotRat#2]
i try to build the exe but some errors occure so please send me the complied exe link please my telegram is https://t.me/EvilCorp_6

**Comment by DARK-DEVIL-66** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Invalid Resx file. Could not find file 'C:\Users\No Name\Pictures\Telegram_BotRat-V_0.1.2a\Telegram_BotRat-V_0.1.2a\TGM_Bot\Resources\StuBot.exe'. Line 126, position 5.	TGM_Bot	C:\Users\No Name\Pictures\Telegram_BotRat-V_0.1.2a\Telegram_BotRat-V_0.1.2a\TGM_Bot\My Project\Resources.resx	126	



Severity	Code	Description	Project	File	Line	Suppression State
Error		Invalid Resx file. Could not find file 'C:\Users\No Name\Pictures\Telegram_BotRat-V_0.1.2a\Telegram_BotRat-V_0.1.2a\StuBot\Resources\WBPV.exe'. Line 135, position 5.	StuBot	C:\Users\No Name\Pictures\Telegram_BotRat-V_0.1.2a\Telegram_BotRat-V_0.1.2a\StuBot\My Project\Resources.resx	135

**Comment by HworangeRival** [comment]
you need to build first the stub, after the main software... the code is all on, i not have anymore src...
